<a href="https://colab.research.google.com/github/tec03/ParaAssignment01-/blob/main/assignment01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# José Mtanous   A00169781@tec.mx
Semana 3

### NumPy Arrays

NumPy es una librería de Python que nos permite realizar operaciones matemáticas de manera compacta y eficiente. Una estructura de datos clave en NumPy es el arreglo, el arreglo de Numpy nos permite realizar operciones matriciales de manera eficiente y compacta. Los arreglos de numpy o ndarray pueden ser de simensions arbitrarias.

In [18]:
oneDimensionArray = np.array([0, 1, 2, 3, 4])
oneDimensionArray

array([0, 1, 2, 3, 4])

In [17]:
twoDimensionArrayOrMatrix = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
twoDimensionArrayOrMatrix

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [21]:
# Al usar arreglos podemos hacer operciones matriciales y vectoriales de manera muy sencilla

import numpy as np
a = np.array([2, 1])
b = np.array([3, 4])

suma = a + b
resta = a - b
division = a / b
hadamard = a * b
productoPunto = np.dot(a,b) # o productoPunto = a.dot(b)


In [23]:
# Tambien podemos extraer partes del arreglo
c = np.array([20, 1, 2, 3, 4])
corte = c[1:4]
corte

array([1, 2, 3])

### APIs

Desde Python podemos acceder a diferentes servicios de una manera abstracta y sencilla usando APIs. Las APIs son analogas a las funciones, es decir, llevan a cabo una tarea y nos abstraen de los detalles de implementación, generalmente para usar un API solo necesitamos proporcionar los datos de entra en un formato correcto. Un ejemplo de uso de API muy usado en Python es la librería de Pandas o la de HTTP. Existen muchísmas librerías que podemos usar en Python para pode acceder a muchismos servicios.

In [ ]:
# Pandas
import pandas as pd
data = {'col_1': [3, 2, 1, 0], 'col_2': ['a', 'b', 'c', 'd']}
pd.DataFrame.from_dict(data)

In [26]:
# HTTP
import requests
url='https://www.ibm.com/'
r=requests.get(url)
r.status_code


200